language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - kerk.chua@ncs.com.sg
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli
  - npm install -g now
script:
  - ng build --prod --base-href https://kerkchern.github.io/bitcoin-order-app/

  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 9430a840357b9d760d1fba0a3c6283782a5c7d8b
  local_dir: dist/bitcoin
  on:
    branch: development
